# Generated by Django 5.2.6 on 2025-09-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=150, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=150, verbose_name="Фамилия"),
            preserve_default=False,
        ),
    ]
