# Generated by Django 5.2.6 on 2025-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, help_text="Введите дату рождения", null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("Senior Administrator", "Старший администратор"),
                            ("Administrator", "Администратор"),
                            ("Waiter", "Официант"),
                            ("Bartender", "Бармен"),
                            ("Sommelier", "Сомелье"),
                            ("Chef", "Шеф-повар"),
                            ("Cook", "Повар"),
                        ],
                        help_text="Выберите должность",
                        max_length=150,
                        verbose_name="Должность",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="employee/avatars", verbose_name="Фото")),
                (
                    "personal_data",
                    models.TextField(
                        blank=True, help_text="Введите личные данные", null=True, verbose_name="Личные данные"
                    ),
                ),
                (
                    "date_employment",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату приема на работу",
                        null=True,
                        verbose_name="Дата приема на работу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
