# Generated by Django 5.2.6 on 2025-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Работает"),
                    ("fired", "Уволен"),
                    ("probationary_period", "Испытательный срок"),
                    ("training", "Отпуск"),
                ],
                default="working",
                help_text="Выберите статус",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
    ]
