# Generated by Django 5.2.6 on 2025-09-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_employee_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "permissions": [("can_view_all_employees", "Может просматривать всех сотрудников")],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
