# Generated by Django 5.2.6 on 2025-09-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_employee_first_name_remove_employee_last_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["id"],
                "permissions": [("can_view_all_employees", "Может просматривать всех сотрудников")],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
