# Generated by Django 5.2.6 on 2025-09-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.IntegerField(help_text="Введите номер стола", unique=True, verbose_name="Номер стола"),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        help_text="Введите количество мест", verbose_name="Количество мест"
                    ),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартный"),
                            ("booth", "Бутылочный"),
                            ("bar", "Барная стойка"),
                            ("vip", "VIP"),
                            ("outdoor", "Уличный"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Тип столика",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание стола", null=True, verbose_name="Описание стола"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Активен ли стол?", verbose_name="Активен")),
                (
                    "min_guests",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Введите минимальное количество гостей",
                        verbose_name="Минимальное количество гостей",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        help_text="Введите максимальное количество гостей",
                        verbose_name="Максимальное количество гостей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(help_text="Количество гостей", verbose_name="Количество гостей"),
                ),
                (
                    "reservation_date",
                    models.DateField(help_text="Дата бронирования", verbose_name="Дата бронирования"),
                ),
                ("start_time", models.TimeField(help_text="Время начала", verbose_name="Время начала")),
                ("end_time", models.TimeField(help_text="Время окончания", verbose_name="Время окончания")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Длительность бронирования в часах", verbose_name="Длительность час"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("canceled", "Отменено"),
                            ("completed", "Завершено"),
                            ("no_show", "Не явился"),
                        ],
                        default="pending",
                        help_text="Статус бронирования",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="Подтверждено ли бронирование?", verbose_name="Подтверждено"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, help_text="Особые пожелания", verbose_name="Особые пожелания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания", verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Дата обновления", verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Столик",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-reservation_date", "start_time"],
            },
        ),
    ]
