# Generated by Django 5.2.6 on 2025-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью стола",
                null=True,
                upload_to="tables/previews",
                verbose_name="Превью",
            ),
        ),
    ]
