# Generated by Django 5.2.6 on 2025-09-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_table_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="seats",
        ),
    ]
