# Generated by Django 5.2.6 on 2025-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_table_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью стола",
                null=True,
                upload_to="booking/tables/previews",
                verbose_name="Превью",
            ),
        ),
    ]
