# Generated by Django 5.2.6 on 2025-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Подтверждено"),
                    ("canceled", "Отменено"),
                    ("completed", "Завершено"),
                    ("no_show", "Не явился"),
                ],
                default="confirmed",
                help_text="Статус бронирования",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
