# Generated by Django 5.2.6 on 2025-09-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_table_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="is_confirmed",
        ),
    ]
