# Generated by Django 5.2.6 on 2025-09-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_reservation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["number"],
                "permissions": [
                    ("administrate_tables", "Может добавлять и редактировать столы"),
                    ("super_administrate_tables", "Может добавлять, редактировать, удалять столы"),
                ],
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
