# Generated by Django 5.2.6 on 2025-09-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_table_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-reservation_date", "start_time"],
                "permissions": [
                    ("can_cancel_reservation", "Может отменять бронирование"),
                    ("can_update_status_reservation", "Может менять статус бронирования"),
                    ("can_delete_reservation", "Может удалять бронирование"),
                    ("can_view_reservation", "Может просматривать бронирование"),
                    ("can_view_reservations", "Может просматривать все бронирования"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
